
jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  timeoutInMinutes: 360
  variables:
    CONFIG: osx_64_numpy1.18python3.7.____cpython
    R_CONFIG: osx_64_r_base4.1
    ARROW_VERSION: 9.0.0.dev91
    UPLOAD_PACKAGES: False
  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      source activate base
      conda config --set channel_priority strict
      conda install -n base -c conda-forge --quiet --yes conda-forge-ci-setup=3 conda-build
    displayName: 'Add conda-forge-ci-setup=3'

  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      /usr/bin/sudo mangle_homebrew
      /usr/bin/sudo -k
    displayName: Mangle homebrew

  - script: |
      git clone --no-checkout --branch master https://github.com/apache/arrow arrow
      git -C arrow checkout d4a7638477769e788030af1e75d55873a92b770b
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow


  - script: |
      source activate base
      echo "Configuring conda."

      setup_conda_rc ./ ./ ./.ci_support/${CONFIG}.yaml
      export CI=azure
      source run_conda_forge_build_setup
      conda update --yes --quiet --override-channels -c conda-forge --all
    displayName: Configure conda and conda-build
    workingDirectory: arrow/dev/tasks/conda-recipes
    env:
      OSX_FORCE_SDK_DOWNLOAD: "1"

  - script: |
      source activate base
      mangle_compiler ./ ./ ./.ci_support/${CONFIG}.yaml
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Mangle compiler

  - script: |
      source activate base
      make_build_number ./ ./ ./.ci_support/${CONFIG}.yaml
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Generate build number clobber file

  - script: |
      source activate base
      set +x
      if [[ "${CONFIG}" == osx_arm* ]]; then
        EXTRA_CB_OPTIONS="${EXTRA_CB_OPTIONS:-} --no-test"
      fi
      conda build arrow-cpp \
        -m ./.ci_support/${CONFIG}.yaml \
        --clobber-file ./.ci_support/clobber_${CONFIG}.yaml \
        ${EXTRA_CB_OPTIONS:-} \
        --output-folder ./build_artifacts

      if [ ! -z "${R_CONFIG}" ]; then
        conda build r-arrow \
          -m ./.ci_support/r/${R_CONFIG}.yaml \
          --output-folder ./build_artifacts
      fi
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Build recipes

  - script: |
     sudo mv /usr/local/conda_mangled/* /usr/local/
    displayName: Unmangle homebrew

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: pip install -e arrow/dev/archery[crossbow-upload]
    displayName: Install Crossbow
  - bash: |
      archery crossbow \
        --queue-path $(pwd) \
        --queue-remote https://github.com/ursacomputing/crossbow \
        upload-artifacts \
        --sha nightly-packaging-2022-05-23-0-azure-conda-osx-clang-py37-r41 \
        --tag nightly-packaging-2022-05-23-0-azure-conda-osx-clang-py37-r41 \
        "arrow/dev/tasks/conda-recipes/build_artifacts/osx-*/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release

  - task: CondaEnvironment@1
    inputs:
      packageSpecs: 'anaconda-client'
      installOptions: '-c conda-forge'
      updateConda: no
  - script: |
      conda install -y anaconda-client
      anaconda -t $(CROSSBOW_ANACONDA_TOKEN) upload --force arrow/dev/tasks/conda-recipes/build_artifacts/osx-*/*.tar.bz2
    displayName: Upload packages to Anaconda
